## 아이리스 다중 분류

In [1]:
import pandas as pd
df = pd.read_csv('../dataset/iris.csv', 
                 names = ["sepal_length", "sepal_width", "petal_length", "petal_width", "species"])
df.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [2]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split, StratifiedKFold

In [3]:
# seed 값 설정
seed = 2020
np.random.seed(seed)
tf.random.set_seed(seed)

In [4]:
dataset = df.values
X = np.array(dataset[:,0:4], dtype=np.float64)
Y_obj = dataset[:,4]

Y_obj[0], Y_obj[50], Y_obj[100]

('Iris-setosa', 'Iris-versicolor', 'Iris-virginica')

In [5]:
e = LabelEncoder().fit(Y_obj)
Y = np.array(e.transform(Y_obj), dtype=np.float64)

In [6]:
Y.shape

(150,)

In [7]:
# 5개로 쪼갬
n_fold = 5
skf = StratifiedKFold(n_splits=n_fold, shuffle=True, random_state=seed)

In [8]:
# 빈 accuracy 리스트
accuracy = []

In [14]:
# One hot encoding
Y_encoded = tf.keras.utils.to_categorical(Y)
Y_encoded[0], Y_encoded[50], Y_encoded[100]

(array([1., 0., 0.], dtype=float32),
 array([0., 1., 0.], dtype=float32),
 array([0., 0., 1.], dtype=float32))

In [15]:
Y_encoded.shape

(150, 3)

In [32]:
Y.shape

(150,)

In [ ]:
# 모델의 설정, 컴파일, 실행
for train, test in skf.split(X, Y):
    model = Sequential([
        Dense(16, input_shape=(4,), activation='relu'),
        Dense(8, activation='relu'), 
        Dense(1, activation='sigmoid')
    ])
#     model.summary()
    model.compile(loss='binary_crossentropy', 
              optimizer='adam',
              metrics=['accuracy'])
    model.fit(X[train], Y[train], epochs=50, batch_size=30, verbose=0)
    
    print(len(X[train]), len(X[test]), end='  ')
    k_accuracy = "%.4f" % (model.evaluate(X[test], Y[test], verbose=0)[1])
    print(k_accuracy)
    accuracy.append(k_accuracy)