# 원, 삼각형, 사각형 구분하기
## 2. 어려운 테스트 문제를 기존 CNN 모델로 푸는 경우

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense, Flatten, Conv2D, MaxPooling2D
from keras.preprocessing.image import ImageDataGenerator

Using TensorFlow backend.


In [2]:
# seed 값 설정
seed = 2020
np.random.seed(seed)
tf.random.set_seed(seed)

### 데이터셋 생성하기

In [3]:
train_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
        'hard_handwriting_shape/train',
        target_size=(24, 24),
        batch_size=3,
        class_mode='categorical')

test_datagen = ImageDataGenerator(rescale=1./255)

test_generator = test_datagen.flow_from_directory(
        'hard_handwriting_shape/test',
        target_size=(24, 24),    
        batch_size=3,
        class_mode='categorical')

Found 45 images belonging to 3 classes.
Found 15 images belonging to 3 classes.


### 모델 구성하기

In [4]:
model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),
                 activation='relu', input_shape=(24,24,3)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(3, activation='softmax'))
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 22, 22, 32)        896       
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 20, 20, 64)        18496     
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 10, 10, 64)        0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 6400)              0         
_________________________________________________________________
dense_1 (Dense)              (None, 128)               819328    
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 387       
Total params: 839,107
Trainable params: 839,107
Non-trainable params: 0
________________________________________________

### 모델 학습과정 설정하기

In [5]:
model.compile(loss='categorical_crossentropy', 
              optimizer='adam', metrics=['accuracy'])

## 모델 학습시키기
- 첫번째 인자 : 훈련데이터셋을 제공할 제네레이터를 지정. 본 예제에서는 앞서 생성한 train_generator으로 지정.
- steps_per_epoch : 한 epoch에 사용한 스텝 수를 지정. 총 45개의 훈련 샘플이 있고 배치사이즈가 3이므로 15 스텝으로 지정.
- epochs : 전체 훈련 데이터셋에 대해 학습 반복 횟수를 지정. 200번을 반복적으로 학습.
- validation_data : 검증데이터셋을 제공할 제네레이터를 지정. 본 예제에서는 앞서 생성한 validation_generator으로 지정.
- validation_steps : 한 epoch 종료 시 마다 검증할 때 사용되는 검증 스텝 수를 지정. 홍 15개의 검증 샘플이 있고 배치사이즈가 3이므로 5 스텝으로 지정.

In [6]:
model.fit_generator(
        train_generator,
        steps_per_epoch=15,
        epochs=200,
        validation_data=test_generator,
        validation_steps=5)

Epoch 1/200
15/15 [==============================] - 1s 38ms/step - loss: 1.1724 - accuracy: 0.5778 - val_loss: 0.9947 - val_accuracy: 0.4000
Epoch 2/200
15/15 [==============================] - 0s 9ms/step - loss: 0.2260 - accuracy: 0.9333 - val_loss: 2.5845 - val_accuracy: 0.3333
Epoch 3/200
15/15 [==============================] - 0s 9ms/step - loss: 0.0097 - accuracy: 1.0000 - val_loss: 2.7716 - val_accuracy: 0.4000
Epoch 4/200
15/15 [==============================] - 0s 11ms/step - loss: 0.0010 - accuracy: 1.0000 - val_loss: 3.3488 - val_accuracy: 0.4000
Epoch 5/200
15/15 [==============================] - 0s 10ms/step - loss: 4.3237e-04 - accuracy: 1.0000 - val_loss: 3.0885 - val_accuracy: 0.4000
Epoch 6/200
15/15 [==============================] - 0s 10ms/step - loss: 3.0924e-04 - accuracy: 1.0000 - val_loss: 4.0467 - val_accuracy: 0.4000
Epoch 7/200
15/15 [==============================] - 0s 9ms/step - loss: 2.1948e-04 - accuracy: 1.0000 - val_loss: 1.8186 - val_accuracy: 0.40

Epoch 57/200
15/15 [==============================] - 0s 10ms/step - loss: 7.0996e-07 - accuracy: 1.0000 - val_loss: 8.9557 - val_accuracy: 0.4000
Epoch 58/200
15/15 [==============================] - 0s 10ms/step - loss: 7.0466e-07 - accuracy: 1.0000 - val_loss: 6.4262 - val_accuracy: 0.4000
Epoch 59/200
15/15 [==============================] - 0s 10ms/step - loss: 6.5962e-07 - accuracy: 1.0000 - val_loss: 4.5163 - val_accuracy: 0.4000
Epoch 60/200
15/15 [==============================] - 0s 10ms/step - loss: 6.3313e-07 - accuracy: 1.0000 - val_loss: 3.7742 - val_accuracy: 0.4000
Epoch 61/200
15/15 [==============================] - 0s 10ms/step - loss: 6.1194e-07 - accuracy: 1.0000 - val_loss: 3.7754 - val_accuracy: 0.4000
Epoch 62/200
15/15 [==============================] - 0s 10ms/step - loss: 5.9340e-07 - accuracy: 1.0000 - val_loss: 4.7765 - val_accuracy: 0.4000
Epoch 63/200
15/15 [==============================] - 0s 10ms/step - loss: 5.7750e-07 - accuracy: 1.0000 - val_loss: 3

15/15 [==============================] - 0s 10ms/step - loss: 1.6159e-07 - accuracy: 1.0000 - val_loss: 7.3270 - val_accuracy: 0.4000
Epoch 113/200
15/15 [==============================] - 0s 10ms/step - loss: 1.5365e-07 - accuracy: 1.0000 - val_loss: 4.0583 - val_accuracy: 0.4000
Epoch 114/200
15/15 [==============================] - 0s 10ms/step - loss: 1.5100e-07 - accuracy: 1.0000 - val_loss: 5.7777 - val_accuracy: 0.4000
Epoch 115/200
15/15 [==============================] - 0s 10ms/step - loss: 1.4570e-07 - accuracy: 1.0000 - val_loss: 4.9522 - val_accuracy: 0.4000
Epoch 116/200
15/15 [==============================] - 0s 10ms/step - loss: 1.4570e-07 - accuracy: 1.0000 - val_loss: 5.7833 - val_accuracy: 0.4000
Epoch 117/200
15/15 [==============================] - 0s 10ms/step - loss: 1.4570e-07 - accuracy: 1.0000 - val_loss: 5.0688 - val_accuracy: 0.4000
Epoch 118/200
15/15 [==============================] - 0s 10ms/step - loss: 1.3775e-07 - accuracy: 1.0000 - val_loss: 0.9703 -

15/15 [==============================] - 0s 10ms/step - loss: 5.8280e-08 - accuracy: 1.0000 - val_loss: 7.8414 - val_accuracy: 0.4000
Epoch 168/200
15/15 [==============================] - 0s 10ms/step - loss: 5.8280e-08 - accuracy: 1.0000 - val_loss: 5.8789 - val_accuracy: 0.4000
Epoch 169/200
15/15 [==============================] - 0s 10ms/step - loss: 5.8280e-08 - accuracy: 1.0000 - val_loss: 1.7988 - val_accuracy: 0.4000
Epoch 170/200
15/15 [==============================] - 0s 10ms/step - loss: 5.8280e-08 - accuracy: 1.0000 - val_loss: 13.5799 - val_accuracy: 0.4000
Epoch 171/200
15/15 [==============================] - 0s 10ms/step - loss: 5.8280e-08 - accuracy: 1.0000 - val_loss: 3.9751 - val_accuracy: 0.4000
Epoch 172/200
15/15 [==============================] - 0s 10ms/step - loss: 5.8280e-08 - accuracy: 1.0000 - val_loss: 6.8165 - val_accuracy: 0.4000
Epoch 173/200
15/15 [==============================] - 0s 11ms/step - loss: 5.5631e-08 - accuracy: 1.0000 - val_loss: 3.3174 

### 모델 평가하기

In [7]:
print("-- Evaluate --")
scores = model.evaluate_generator(test_generator, steps=5)
print("%s: %.2f%%" %(model.metrics_names[1], scores[1]*100))

-- Evaluate --
accuracy: 40.00%


### 모델 사용하기

In [8]:
print("-- Predict --")
output = model.predict_generator(test_generator, steps=5)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(test_generator.class_indices)
print(output)

-- Predict --
{'circle': 0, 'rectangle': 1, 'triangle': 2}
[[0.003 0.015 0.982]
 [0.000 0.000 1.000]
 [0.765 0.000 0.235]
 [0.000 0.000 1.000]
 [0.000 0.000 1.000]
 [0.000 0.000 1.000]
 [0.000 0.003 0.997]
 [0.000 0.000 1.000]
 [0.000 0.000 1.000]
 [0.000 0.062 0.938]
 [0.000 0.000 1.000]
 [0.000 0.000 1.000]
 [0.000 0.006 0.994]
 [0.590 0.004 0.406]
 [0.000 0.004 0.996]]


In [9]:
for i in range(len(test_generator.labels)):
    print(test_generator.filenames[i], test_generator.labels[i], np.argmax(output[i]))

circle\circle021.png 0 2
circle\circle022.png 0 2
circle\circle023.png 0 0
circle\circle024.png 0 2
circle\circle025.png 0 2
rectangle\rectangle021.png 1 2
rectangle\rectangle022.png 1 2
rectangle\rectangle023.png 1 2
rectangle\rectangle024.png 1 2
rectangle\rectangle025.png 1 2
triangle\triangle021.png 2 2
triangle\triangle022.png 2 2
triangle\triangle023.png 2 2
triangle\triangle024.png 2 0
triangle\triangle025.png 2 2
